### ISSUE TITLE
disease and conditions

### ISSUE THREAD

**Issue by lpicci96** [ONEcampaign/topic_health_financing#42]
2 chart ideas:
1. time series showing total financing going towards each disease - https://public.flourish.studio/visualisation/14182221/ 
2. sankey (of latest values, since the time series is not extensive) showing financing flows from source to disease - https://public.flourish.studio/visualisation/13994099/

Comment from Nupur:
> The sankey is amazing and so fascinating. I think we would need to find a way to really stress or highlight that domestic private is being largely driven by out-of-pocket spending. Bc the amount is so large and I could see a world in which it could be confused as private sector spending, but we def can't relabel it as "out of pocket spending" bc it's not all that is included in domestic private. Maybe as an annotation or like in the footnote? For the line chart, I really like this, but do you think we could show it as a share of total health spending?? After seeing the charts next to each other, I think we'd be okay with just showing one chart (the sankey) instead of two

The data is not disaggregated for OOP, but this point can be included in the text. Because there is a lot of information that can potentially be displayed, there is no single chart that covers it all so it is a matter of compromise to show the things that are more important - either showing the time series and "total values" in a line chart or showing the breakdown by source in the sankey but not showing the time series.

Open to further suggestions @jm-rivera @nupur-parikh

**Comment by nupur-parikh** [comment]
Thanks @lpicci96 ! I'm okay to just show one chart, I know there's a lot we can show so I think showing one chart breaking down financing by source like the sankey for the most current year is good. As long as we can emphasize somwhere in the text and/or as a footnote on the chart (?) that the data is not disaggregated for OOP and that domestic private includes OOPS. 

Do you think this could cause confusion with the way we name indicators in the what are the main sources section of the page? @jm-rivera I'm thinking of our conversation about defining "total health spending" vs. "government spending" as a share of government spending, so would love your thoughts on this if you have any!  If so, I think we just go with one chart that shows total values in a line chart as a share of total health spending over time.

**Comment by jm-rivera** [comment]
Thanks both! 

I actually see value in both charts. The sankey is a great presentation of where the flows are coming from and where they are going to. Very visual, easy to get a quick sense of how certain diseases are getting financed, etc. While the same data, seeing total spending by disease - as a trend, and being able to add multiple diseases to the same view - could be very valuable to people. You select a country, create your own mix of diseases, and screenshot. If we're not pressed for space, I think we should keep both.

On the labelling question, my suggestion would be to rename things. What is domestic private made up? Name it that (out of pocket and other domestic private?). What is external? (external aid?). Same for government. Giving these labels clear names will be important - you can always refer to the original indicator names in the footnote. With this exercise the important thing is clarity for the user (i.e. that they really understand what they are looking at), rather than strict adherence to the terminology used by the source (but still good practise to say somewhere what the original names were).

On viz specific comment on the Sankey. I think we should be parsimonious with our use of colour. I don't know how the template may limit us in that regard, but maybe a colour to identify each of the sources, but no colour differentiation between diseases (as there are too many)

**Comment by nupur-parikh** [comment]
Thanks Jorge! I think we should have room on the page for both charts, I think these would be the last two we add to the page for the foreseeable future, but @lpicci96 let me know if you don't think it's feasible. 

Great idea on renaming the labels, can we rename as follows:
external --> external aid
domestic private --> Out-of-pocket & other private *
government--> domestic government

* For the footnote: This represents domestic private financing which is comprised of out of pocket spending and other domestic private sources of health financing.

Happy to just use colors for sources rather than sources & diseases, but Luca please correct me if I'm wrong on the capabilities of the sankey
